#!/bin/bash

#system information
HOSTNAME=$(hostname)
OS=$(awk -F= '/^NAME/{print $2}' /etc/os-release | sed 's/"//g')
UPTIME=$(uptime -p)

#hardware information
CPU=$(lshw -class processor | awk '/product/{print $2" "$3" "$4; exit}')
CPU_SPEED=$(lscpu | awk '/^CPU MHz/{printf "%.2f GHz", $3/1000}')
MAX_CPU_SPEED=$(lscpu | awk '/^CPU max MHz/{printf "%.2f GHz", $4/1000}')
RAM=$(free -h | awk '/^Mem/{print $2}')
DISK=$(lsblk -o NAME,MODEL,SIZE | grep -v "NAME\|loop" | awk '{print $2" "$3}')

#network information
FQDN=$(hostname -f)
HOST_IP=$(ip a | awk '/inet / && !/127.0.0.1/{print $2}')
GATEWAY_IP=$(ip r | awk '/default/{print $3}')
DNS_SERVER=$(cat /etc/resolv.conf | awk '/^nameserver/{print $2}')

#interface information
INTERFACE=$(lshw -class network | awk '/logical name:/{print $3; exit}')
INTERFACE_MODEL=$(lshw -class network | awk '/product/{print $2" "$3}')

#system status
USERS=$(who | awk '{print $1}' | sort | uniq | tr '\n' ',')
DISK_SPACE=$(df -h --output=source,avail | awk 'NR>1{print $1" "$2}')
PROCESS_COUNT=$(ps aux | wc -l)
LOAD_AVERAGES=$(cat /proc/loadavg | awk '{print $1", "$2", "$3}')
MEMORY=$(free -m | awk '/Mem/{print $3"M / "$2"M"}')
LISTENING_PORTS=$(ss -tuln | awk '/LISTEN/{print $5}' | cut -d: -f2 | sort -n | uniq | tr '\n' ',')
UFW_RULES=$(ufw status numbered | grep -Eo '[0-9]+/.*ALLOW.*' | tr '\n' ', ')

# report
cat <<EOF

System Report generated by $(whoami) on $(date +"%Y-%m-%d %H:%M:%S")

System Information
------------------
Hostname: $HOSTNAME
OS: $OS
Uptime: $UPTIME

Hardware Information
--------------------
CPU: $CPU
Speed: $CPU_SPEED (Max: $MAX_CPU_SPEED)
RAM: $RAM
Disk(s): $DISK
Video: $(lspci | grep -i vga | awk -F': ' '{print $2}')

Network Information
-------------------
FQDN: $FQDN
Host Address: $HOST_IP
Gateway IP: $GATEWAY_IP
DNS Server: $DNS_SERVER

Interface: $INTERFACE
Model: $INTERFACE_MODEL
IP Address: $(ip a show $INTERFACE | awk '/inet /{print $2}')

System Status
-------------
Users Logged In: ${USERS%,}
Disk Space: $DISK_SPACE
Process Count: $PROCESS_COUNT
Load Averages: $LOAD_AVERAGES
Memory Allocation: $MEMORY
Listening Network Ports: ${LISTENING_PORTS%,}
UFW Rules: ${UFW_RULES%,}

EOF
